replicaCount: 

resources:
  requests:
    cpu: 40m
    memory: 40M

ingress:
  hosts:
    - host: abc-dev.azurelaboratory.com
      paths:
        - path: /
          pathType: Prefix
  tls:
    - secretName: abc-dev-tls
      hosts:
        - abc-dev.azurelaboratory.com